indent_style = "Block"
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
fn_params_layout = "Vertical"
fn_single_line = true
hard_tabs = true
format_strings = true
normalize_comments = true
reorder_imports = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
edition = "2021"
max_width = 100
tab_spaces = 4
