[package]
name = "common_utils"
version.workspace = true
edition.workspace = true
authors.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml.workspace = true
serde.workspace = true